# Generated by Django 2.0.2 on 2018-03-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
