# Generated by Django 2.0.2 on 2018-03-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chats', '0003_auto_20180323_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('channel', 'Channel'), ('group', 'Group'), ('private', 'Private')],
                                   db_index=True, max_length=24, verbose_name='Chat type'),
        ),
    ]
