# coding: utf-8

STATE_END = -1

AUTH_STATE_EMAIL = 0
AUTH_STATE_CAPTCHA = 1
AUTH_STATE_PASSWORD = 2

TOPIC_STATE_TYPE = 'type'
TOPIC_STATE_TITLE = 'title'
TOPIC_STATE_BODY = 'body'

TOPIC_STATE_EDIT = 'edit'
TOPIC_STATE_EDIT_CHOOSE_TOPIC = 'edit-choose-topic'
TOPIC_STATE_EDIT_CHOOSE_PART = 'edit-choose-part'

TOPIC_STATE_DELETE = 'delete'

TOPIC_STATE_PARENTS = 'parents'
TOPIC_STATE_CALLBACK = 'callback'
