# coding: utf-8

STATE_END = -1

AUTH_STATE_EMAIL = 0
AUTH_STATE_CAPTCHA = 1
AUTH_STATE_PASSWORD = 2

TOPIC_STATE_TITLE = 'title'
TOPIC_STATE_BODY = 'body'

TOPIC_STATE_UPDATE = 'update'
TOPIC_STATE_DELETE = 'delte'

TOPIC_STATE_PARENTS = 'parents'
TOPIC_STATE_CALLBACK = 'callback'
