# coding: utf-8

TOPIC_TYPE_NEED = 'need'
TOPIC_TYPE_GOAL = 'goal'
TOPIC_TYPE_IDEA = 'idea'
TOPIC_TYPE_PLAN = 'plan'
TOPIC_TYPE_STEP = 'step'
TOPIC_TYPE_TASK = 'task'

TOPIC_TYPES_LIST = (
    TOPIC_TYPE_NEED,
    TOPIC_TYPE_GOAL,
    TOPIC_TYPE_IDEA,
    TOPIC_TYPE_PLAN,
    TOPIC_TYPE_STEP,
    TOPIC_TYPE_TASK
)
